name: test
on:
  push:
    branches:
      - "**"
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version-file: 'go.mod'
      - name: lint
        run: |
          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
          bin/golint -set_exit_status ./...
      - name: vet
        run: |
          go vet ./...
      - name: test
        run: |
          make test
  docker-build-test:
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v4
       with:
         fetch-depth: 1
     - name: Build container image
       uses: docker/build-push-action@v5
       with:
         push: false
         tags: ${{ steps.meta.outputs.tags }}
